- hosts: nagios-server
  remote_user: root
  sudo: yes
  roles:
  - prerequisites
  - nagios-server
- hosts: nagios-agents
  remote_user: root
  sudo: yes
  roles:
  - nagios-agent
- hosts: nagios-server
  remote_user: root
  sudo: yes
  roles:
  - nagios-monitor-target