- name: Ensure target configuration files exist
  file: dest=/usr/local/nagios/etc/servers state=directory
- copy: src={{ item }} dest=/usr/local/nagios/etc/servers/ mode='u=rw,g=r,o=r'
  with_fileglob:
    - "{{ playbook_dir }}/target-configurations/*"
- name: Restart nagios service
  service: name=nagios state=restarted